version: '3'

services:
  db:
    container_name: app-database
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db

  backend:
    container_name: app-server
    build:
      context: .
      dockerfile: ./compose/local/backend/Dockerfile
    command: /start
    tty: true
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env/.env.local
    depends_on:
      - db

  frontend:
    container_name: app-client
    build:
      context: .
      dockerfile: ./compose/local/frontend/Dockerfile
    # docker run -i
    stdin_open: true
    volumes:
      - './frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3000:3000
    # docker run -t. keep the container running
    tty: true
    environment:
      - NODE_ENV=development
      - PUBLIC_URL=http://0.0.0.0:3000/
    depends_on:
      - backend
